### ISSUE TITLE
Fastest way to grab a full frame image (uncompressed)?

### ISSUE THREAD

**Issue by Rosentorp** [waveform80/picamera#467] opened 2018-01-31 07:45 UTC
Actually two questions:

1. How fast can you take an full fram picture (with the v2 camera and uncompressed result)?

2. Example on how to do the above?

Thanks in advance!

/Anders

**Comment by 6by9** [comment] 2018-01-31 12:38
Duplicate of forum post - https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=204108

**Closed** 2018-09-28 22:11 UTC
