### ISSUE TITLE
Is there any method to draw some basic shape on camera output?

### ISSUE THREAD

**Issue by sczhengyabin** [waveform80/picamera#367] opened 2017-02-06 02:37 UTC
For example, I want to draw a rect on people face that my code detected. 
I can't figure out a way to do it, the overlay function can only effect the whole output.
A RGBA overlay will do, but according to #199 , yet to have one right now.

**Comment by waveform80** [comment] 2017-02-06 21:34
Duplicate of #196; this will be in 1.13 but via a low level API (mmalobj; not directly via the higher level PiCamera API)

**Closed by waveform80** 2017-02-06 21:34 UTC
Labels: duplicate
