### ISSUE TITLE
Not supported in bullseye Raspberry Pi OS version

### ISSUE THREAD

**Issue by Bart63** [waveform80/picamera#711] opened 2021-11-14 13:32 UTC
With the 2021-10-30 release of RPi OS raspistill and raspivid are now replaced with libcamera-still and libcamera-vid.
And now picamera package does not work.

**Comment by mitchelr** [comment] 2021-11-15 22:34
Are we awaiting the python module for the Libcamera library?

**Comment by beniroquai** [comment] 2021-11-21 14:24
That was indeed a bit of a surprise.

**Comment by 6by9** [comment] 2021-11-24 17:24
Raspistill and vid are not related to this repo.
Usage with picamera is a duplicate of #697.

**Closed as completed by 6by9** 2021-11-24 17:24 UTC
