### ISSUE TITLE
save preview to file instead of a display device?

### ISSUE THREAD

**Issue by withr** [waveform80/picamera#349] opened 2016-11-29 11:19 UTC
I know picamera can record video / take picture when it streaming preview to screen. And I know also it can't write the preview to file, like /home/user/preview.jpg. But that's feature is actually very useful, for example, it can same the preview to any computer through internet, user can add text /shapes /watermark to the preview.  RPi_Cam_Web_Interface has this feature, but still very limited. 

Could you tell me where to modify the preview output from the source code? Or is it possible ?

Thanks!

**Comment by waveform80** [comment] 2016-11-30 10:19
This is effectively a duplicate of #196. Watch that space...

**Closed** 2016-11-30 10:20 UTC
Labels: duplicate
