### ISSUE TITLE
Add sound to the recording

### ISSUE THREAD

**Issue by Giladkapel** [waveform80/picamera#298] opened 2016-06-26 17:18 UTC
Hi,
Is there a way to add sound (a mic connected to a GPIO) to a recording?
If not, any chance this can be added tot he 'requested features' list?
Tnx
Gilad.

**Comment by fodiator** [comment] 2016-09-17 09:17
I would like to hook up to this question
Is tehre any way to record audio channels as well?

**Comment by waveform80** [comment] 2017-02-02 23:44
Duplicate of #246 - it's not something I know much about (never experimented with audio encoding or muxing via MMAL, though I assume such things are possible); but if people want to contribute code / recipes I'm happy to add them!

**Closed by waveform80** 2017-02-02 23:44 UTC
